### ISSUE TITLE
How to support sub.sub.example.com?

### ISSUE THREAD

**Issue by nuomi1** [zastrixarundell/caddy-cloudflare#1]
Here is my configuration.

⬇️⬇️⬇️

## Caddyfile

```caddy
{
	email {env.tls_email}
}

(root-caddy) {
	root * /usr/share/caddy
	file_server
}

(https-cloudflare) {
	tls {
		dns cloudflare {env.dns_cloudflare_api_token}
	}
}

(respond-abort) {
	handle {
		abort
	}
}

(handle-errors) {
	handle_errors {
		respond "{err.status_code} {err.status_text}"
	}
}

*.sub.example.com {
	import https-cloudflare

	@sub host sub.sub.example.com
	handle @sub {
		import root-caddy
	}

	import respond-abort
	import handle-errors
}
```

## Cloudflare Tunnels

- Public hostname: sub.sub.example.com
- Path: *
- Service: https://caddy:443
- Origin configurations: originServerName: *.sub.example.com

## Result

```bash
curl -I https://sub.sub.example.com
curl: (35) LibreSSL/3.3.6: error:1404B410:SSL routines:ST_CONNECT:sslv3 alert handshake failure
```

DNS Record shows `This hostname is not covered by a certificate.`

**Comment by zastrixarundell** [comment]
I don't think you can on a free cloudflare profile. I've had [this issue](https://caddy.community/t/how-would-i-setup-caddy-with-cloudflare-to-hide-my-ip-using-wildcard-dns-records/21018/7) before even without tunnels. Basically cloudflare supports `example.com` and `*.example.com`, not `*.sub.example.com`. You'd need to pay ~10 euros a month for that and decided that I'm just not going to do it.

**Comment by zastrixarundell** [comment]
So basically in order to support *.sub.example.com you can create a wildcard dns without a tunnel and proxy. Otherwise you'll have to get creative with names likes `sub-sub.example.com`, it's not the best solution but it's free :shrug: .

**Comment by nuomi1** [comment]
> So basically in order to support *.sub.example.com you can create a wildcard dns without a tunnel and proxy. Otherwise you'll have to get creative with names likes `sub-sub.example.com`, it's not the best solution but it's free 🤷 .

Thanks. 😭😭😭

**Comment by zastrixarundell** [comment]
@nuomi1 from what I *know* you can do this with `sub.sub.example.com` but you would need to have to go to for a premium plan on cloudflare. I haven't done that yet so I don't know how to set it up.
